### ISSUE TITLE
[MEGA CNC Alpha] Missing temperature graph, Apexchart config could be different to improve visibility

### ISSUE THREAD

**Issue by kamilzierke** [alex3dbros/megacnc#1]
Missing temperature graph as below:

![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/909619bb-ce30-4831-9478-384d3c25ef52)

**Comment by kamilzierke** [comment]
![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/e1aa3329-f254-41af-bd4f-ae989ebbcb9e)
Different example of Apexcharts config, improving visibility of Voltage/Current. Temperature in the brush graph below main one.

![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/67feff65-954a-452e-924f-d6e53f24030a)


Just an example.

**Comment by kamilzierke** [comment]
The above was actually an Apexcharts.js implementation in Home Assistant done by https://github.com/RomRider/apexcharts-card
The card translated to Apexcharts.js should look something like this:

var options = {
  chart: {
    type: 'line',
    height: 350,
    toolbar: {
      show: true,
      tools: {
        selection: true
      }
    },
    brush: {
      enabled: true,
      target: 'chart',
    },
    selection: {
      enabled: true,
      xaxis: {
        min: new Date('2023-01-01').getTime(),
        max: new Date('2023-01-01').getTime() + 3600000 // 1 hour in milliseconds
      }
    }
  },
  series: [
    {
      name: 'Voltage',
      data: [] // Populate with actual data for 'sensor.mcc_cell_01_vlt'
    },
    {
      name: 'Temperature',
      data: [] // Populate with actual data for 'sensor.mcc_cell_01_tmp'
    },
    {
      name: 'Current',
      data: [] // Populate with actual data for 'sensor.mcc_cell_01_amp'
    }
  ],
  title: {
    text: 'Cell 01',
    align: 'left'
  },
  stroke: {
    width: 2
  },
  markers: {
    size: 0
  },
  tooltip: {
    shared: true,
    intersect: false,
    x: {
      format: 'dd MMM - HH:mm'
    }
  },
  xaxis: {
    type: 'datetime'
  },
  yaxis: [{
    title: {
      text: 'Voltage',
    },
  }, {
    opposite: true,
    title: {
      text: 'Temperature'
    }
  }, {
    opposite: true,
    title: {
      text: 'Current'
    }
  }],
  legend: {
    show: true
  }
};

var chart = new ApexCharts(document.querySelector("#chart"), options);
chart.render();

**Comment by alex3dbros** [comment]
I added the temperature to replace the capacity. I will close the issue for now as I have an open issue with graph becoming unresponsive.
