### ISSUE TITLE
[MEGA CNC Alpha / MCC FW] Capacity resets before taking out the measured cell from the slot, starts the mCAP cycle anew. Timer not reset.

### ISSUE THREAD

**Issue by kamilzierke** [alex3dbros/megacnc#4]
All measurements resets before taking out the measured cell from the slot.
The workflow was started, ESR measurement, capacity and bringing the cell to the storage voltage were completed. 
Before the cell was taken out from the slot everything was reset:

![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/e9d4453b-cd3d-4661-a0ca-a15a0fb453d5)
![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/53d9e63a-72aa-4735-aca7-faa030033e33)
![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/84e664ea-36fc-41d0-9c3c-630f9f695242)

**Comment by alex3dbros** [comment]
The reset could happen only if the device actually reset. Please try to reproduce or find a way to check this

**Comment by kamilzierke** [comment]
![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/315451ed-1263-4109-9af0-1f4ba292ed59)

Unfortunately I don't know how to replicate it, it doesn't happen all the time, rather random.
The device was not reset (there was ongoing charging on slot 8)

**Comment by kamilzierke** [comment]
Another observation: the mCAP timer was not reset and continue normally.

![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/248db941-e01d-4911-b858-01c17c543736)


Adding also CSV with history data gathered from API.
[history.csv](https://github.com/alex3dbros/megacnc/files/14390870/history.csv)

**Comment by kamilzierke** [comment]
Probably we should change the classification of this error from MEGA CNC to FW issue; I was running mCAP through and API and gathering data the same way, MEGA CNC was not involved directly.

**Comment by alex3dbros** [comment]
I think a charge command was sent to your device. That will reset the capacity but not the counter. That explains the reason for showing sudden voltage raise. You can reproduce this behaviour by sending a charge command after store state is reached. At that point the capacity counter is being reset.

**Comment by kamilzierke** [comment]
I wasn't able to replicate the same situation when operating only through the MCC device menu, but I was able to replicate the issue with resetting capacity measurement:

![obraz](https://github.com/alex3dbros/megacnc/assets/67487992/e48974dd-aa64-49ca-9d03-2a395630f9f8)

After 2hrs of sitting in the slot (1:59h for cell 1, 2:06hr for cell 8) the counter was reset and the cell status changed to "Regular cell"

**Comment by alex3dbros** [comment]
Try to make a video of the device display to make sure it does not reset. Also, are you doing any api request with your custom monitoring software directly to megacell charger? There's a certain number of cells you can request info for from the device to avoid memory overflow.

**Comment by kamilzierke** [comment]
In the previous example I was running the below:

rest:
  - resource: http://192.168.1.156/api/get_cells_info
    method: POST
    headers:
      Content-Type: "application/json"
    payload: '{"start": 1, "end": 16}'
    scan_interval: 15
    timeout: 30

So basically I'm requesting every cell info every 15s.

**Comment by alex3dbros** [comment]
Ok, that's the problem. Split that request in 2 different requests, 1 to 8 and 9 to 16 and you won't have that issue.
